before_cache:
- sudo rm -rf $HOME/.m2/repository/com/yahoo/vespa
- sudo rm -rf $HOME/.m2/repository/repository.xml
- du --summarize --human-readable $HOME/.m2/repository
- du --summarize --human-readable $HOME/.ccache
- rm -rf $HOME/CACHE; find $TRAVIS_BUILD_DIR -name .starts | while read line; do du
  -sh $line;         DIR=$(dirname $HOME/CACHE$line); mkdir -p $DIR; cp -r $line $DIR;
  done
- find $TRAVIS_BUILD_DIR -name jdeps-cache | while read line; do du -sh $line;         DIR=$(dirname
  $HOME/CACHE$line); mkdir -p $DIR; cp -r $line $DIR; done
- echo CACHESIZE $(du -sk $HOME/CACHE)
before_install:
- wget http://mir.cs.illinois.edu/awshi2/starts-1.4.zip -P $HOME
- unzip $HOME/starts-1.4.zip -d $HOME/.m2/repository
- find $HOME/CACHE -name jdeps-cache | while read line; do du -sh $line;         DIR=$(dirname
  ${line#$HOME/CACHE}); if [[ -d ${DIR#jdeps-cache/} ]]; then cp -r $line $DIR; fi;
  done
- find $HOME/CACHE -name .starts | while read line; do du -sh $line;         DIR=$(dirname
  ${line#$HOME/CACHE}); if [[ -d ${DIR#.starts/} ]]; then cp -r $line $DIR; fi; done
before_script:
- find $TRAVIS_BUILD_DIR -name .starts | while read line; do rm -rf $line; done
- find $TRAVIS_BUILD_DIR -name jdeps-cache | while read line; do rm -rf $line; done
- find $HOME/CACHE -name jdeps-cache | while read line; do du -sh $line;         DIR=$(dirname
  ${line#$HOME/CACHE}); if [[ -d ${DIR#jdeps-cache/} ]]; then cp -r $line $DIR; fi;
  done
- find $HOME/CACHE -name .starts | while read line; do du -sh $line;         DIR=$(dirname
  ${line#$HOME/CACHE}); if [[ -d ${DIR#.starts/} ]]; then cp -r $line $DIR; fi; done
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ccache
  - $HOME/CACHE
  timeout: 900
install: true
language: minimal
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- ./travis/travis.sh
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
services:
- docker
sudo: required
